// Generated by CoffeeScript 1.7.1
(function() {
  var app, port;

  app = require(process.cwd() + '/app');

  port = app.port;

  app.listen(port, function() {
    return console.log("listening on port " + port);
  });

}).call(this);
